use std::sync::Arc;

use crate::types::{ChatMessage, GenerateParams};

/// Text generated by an engine with accounting metadata.
///
/// # Example
///
/// ```
/// use server::GeneratedText;
///
/// let output = GeneratedText::new("hello", 1);
/// assert_eq!(output.text(), "hello");
/// assert_eq!(output.tokens(), 1);
/// ```
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedText {
    text: String,
    tokens: usize,
}

impl GeneratedText {
    /// Creates generated text with a token count.
    pub fn new(text: impl Into<String>, tokens: usize) -> Self {
        Self {
            text: text.into(),
            tokens,
        }
    }

    /// Returns generated text.
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Consumes the value and returns generated text.
    pub fn into_text(self) -> String {
        self.text
    }

    /// Returns generated token count.
    pub const fn tokens(&self) -> usize {
        self.tokens
    }
}

/// Minimal inference surface required by the HTTP server.
///
/// This keeps the server crate decoupled from a specific scheduler/executor
/// implementation while preserving the critical shared engine handle in
/// `AppState`.
pub trait EngineHandle: Send + Sync + 'static {
    /// Returns the model id exposed by API responses.
    fn model_id(&self) -> &str;
    /// Counts prompt text tokens.
    fn count_tokens(&self, text: &str) -> crate::Result<usize>;
    /// Counts chat message tokens.
    fn count_message_tokens(&self, messages: &[ChatMessage]) -> crate::Result<usize>;
    /// Renders chat messages into a prompt.
    fn apply_chat_template(&self, messages: &[ChatMessage]) -> crate::Result<String>;
    /// Generates all response text and usage metadata.
    fn generate_with_usage(
        &self,
        prompt: &str,
        params: GenerateParams,
    ) -> crate::Result<GeneratedText>;
    /// Generates response chunks for SSE streaming.
    fn generate_tokens(&self, prompt: &str, params: GenerateParams) -> crate::Result<Vec<String>>;
}

/// Shared engine pointer stored in router state.
pub type SharedEngine = Arc<dyn EngineHandle>;

/// Deterministic engine used by the server until the workspace engine exposes a
/// full public inference entry point.
///
/// `EchoEngine` still exercises the same OpenAI request handling, token
/// accounting, non-streamed response, and SSE streamed response paths as a real
/// model-backed implementation.
///
/// # Example
///
/// ```
/// use server::{EchoEngine, EngineHandle, GenerateParams};
///
/// let engine = EchoEngine::new("demo");
/// let chunks = engine.generate_tokens("hello world", GenerateParams::default()).unwrap();
/// assert!(!chunks.is_empty());
/// assert_eq!(engine.model_id(), "demo");
/// ```
#[derive(Clone, Debug)]
pub struct EchoEngine {
    model_id: String,
}

impl EchoEngine {
    /// Creates an engine that derives deterministic text from the prompt.
    pub fn new(model_id: impl Into<String>) -> Self {
        Self {
            model_id: model_id.into(),
        }
    }
}

impl EngineHandle for EchoEngine {
    fn model_id(&self) -> &str {
        &self.model_id
    }

    fn count_tokens(&self, text: &str) -> crate::Result<usize> {
        Ok(count_words(text))
    }

    fn count_message_tokens(&self, messages: &[ChatMessage]) -> crate::Result<usize> {
        Ok(messages
            .iter()
            .map(|message| count_words(message.content()))
            .sum())
    }

    fn apply_chat_template(&self, messages: &[ChatMessage]) -> crate::Result<String> {
        Ok(messages
            .iter()
            .map(|message| format!("{}: {}", message.role(), message.content()))
            .collect::<Vec<_>>()
            .join("\n"))
    }

    fn generate_with_usage(
        &self,
        prompt: &str,
        params: GenerateParams,
    ) -> crate::Result<GeneratedText> {
        let tokens = self.generate_tokens(prompt, params)?;
        Ok(GeneratedText::new(tokens.concat(), tokens.len()))
    }

    fn generate_tokens(&self, prompt: &str, params: GenerateParams) -> crate::Result<Vec<String>> {
        let mut words = prompt
            .split_whitespace()
            .rev()
            .take(params.max_tokens())
            .peekable();
        let mut chunks = Vec::new();

        if words.peek().is_none() {
            chunks.push("ok".to_string());
            return Ok(chunks);
        }

        for word in words {
            let mut chunk = word.to_string();
            if !params.stop().iter().any(|stop| chunk.contains(stop)) {
                chunk.push(' ');
                chunks.push(chunk);
            }
        }
        Ok(chunks)
    }
}

fn count_words(text: &str) -> usize {
    text.split_whitespace().count().max(1)
}
