use std::sync::Arc;

use ::engine::{GenerationConfig, GenerationEngine};
use tokenizer::TokenizerWrapper;

use crate::config::ServerConfig;
use crate::types::{ChatMessage, GenerateParams};

/// Text generated by an engine with accounting metadata.
///
/// # Example
///
/// ```
/// use server::GeneratedText;
///
/// let output = GeneratedText::new("hello", 1);
/// assert_eq!(output.text(), "hello");
/// assert_eq!(output.tokens(), 1);
/// ```
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedText {
    text: String,
    tokens: usize,
}

impl GeneratedText {
    /// Creates generated text with a token count.
    pub fn new(text: impl Into<String>, tokens: usize) -> Self {
        Self {
            text: text.into(),
            tokens,
        }
    }

    /// Returns generated text.
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Consumes the value and returns generated text.
    pub fn into_text(self) -> String {
        self.text
    }

    /// Returns generated token count.
    pub const fn tokens(&self) -> usize {
        self.tokens
    }
}

/// Minimal inference surface required by the HTTP server.
///
/// This keeps the server crate decoupled from a specific scheduler/executor
/// implementation while preserving the critical shared engine handle in
/// `AppState`.
pub trait EngineHandle: Send + Sync + 'static {
    /// Returns the model id exposed by API responses.
    fn model_id(&self) -> &str;
    /// Counts prompt text tokens.
    fn count_tokens(&self, text: &str) -> crate::Result<usize>;
    /// Counts chat message tokens.
    fn count_message_tokens(&self, messages: &[ChatMessage]) -> crate::Result<usize>;
    /// Renders chat messages into a prompt.
    fn apply_chat_template(&self, messages: &[ChatMessage]) -> crate::Result<String>;
    /// Generates all response text and usage metadata.
    fn generate_with_usage(
        &self,
        prompt: &str,
        params: GenerateParams,
    ) -> crate::Result<GeneratedText>;
    /// Generates response chunks for SSE streaming.
    fn generate_tokens(&self, prompt: &str, params: GenerateParams) -> crate::Result<Vec<String>>;
}

/// Shared engine pointer stored in router state.
pub type SharedEngine = Arc<dyn EngineHandle>;

/// HTTP-facing adapter around the workspace generation engine.
///
/// The server owns request shaping, chat templating, token counting, and text
/// decoding. Model loading, architecture routing, and token generation stay in
/// the `model` and `engine` crates.
///
/// # Example
///
/// ```no_run
/// use server::{EngineHandle, ServerConfig, ServerEngine};
///
/// # fn main() -> anyhow::Result<()> {
/// let config = ServerConfig::from_env();
/// let engine = ServerEngine::load(&config)?;
/// assert_eq!(engine.model_id(), config.model);
/// # Ok(())
/// # }
/// ```
pub struct ServerEngine {
    engine: GenerationEngine,
    tokenizer: TokenizerWrapper,
}

impl ServerEngine {
    /// Loads the workspace generation engine and tokenizer assets.
    pub fn load(config: &ServerConfig) -> anyhow::Result<Self> {
        let engine = GenerationEngine::load_cuda0(config.model.clone(), None)?;
        let assets = engine.tokenizer_assets();
        let tokenizer = TokenizerWrapper::from_file(
            assets.tokenizer_path(),
            assets.tokenizer_config_path(),
            assets.chat_template_path(),
        )?;

        Ok(Self { engine, tokenizer })
    }

    fn generate(&self, prompt: &str, params: GenerateParams) -> anyhow::Result<GeneratedText> {
        let input_ids = self.tokenizer.encode(prompt)?;
        let config = GenerationConfig::new(
            params.max_tokens(),
            params.temperature() as f64,
            params.top_p() as f64,
            params.top_k(),
        )?;
        let output = self
            .engine
            .generate(&input_ids, config, |token| self.tokenizer.is_eos(token))?;
        let tokens = output.tokens();
        let text = self.tokenizer.decode(output.token_ids())?;
        Ok(GeneratedText::new(
            trim_at_stop(text, params.stop()),
            tokens,
        ))
    }
}

impl EngineHandle for ServerEngine {
    fn model_id(&self) -> &str {
        self.engine.model_id()
    }

    fn count_tokens(&self, text: &str) -> crate::Result<usize> {
        self.tokenizer
            .count_text_tokens(text)
            .map_err(|err| anyhow::Error::from(err).into())
    }

    fn count_message_tokens(&self, messages: &[ChatMessage]) -> crate::Result<usize> {
        let prompt = self.apply_chat_template(messages)?;
        self.count_tokens(&prompt)
    }

    fn apply_chat_template(&self, messages: &[ChatMessage]) -> crate::Result<String> {
        let messages = messages
            .iter()
            .map(ChatMessage::to_tokenizer_message)
            .collect::<Vec<_>>();
        self.tokenizer
            .apply_chat_template(&messages)
            .or_else(|_| fallback_chat_template(&messages))
            .map_err(|err| anyhow::Error::from(err).into())
    }

    fn generate_with_usage(
        &self,
        prompt: &str,
        params: GenerateParams,
    ) -> crate::Result<GeneratedText> {
        self.generate(prompt, params).map_err(Into::into)
    }

    fn generate_tokens(&self, prompt: &str, params: GenerateParams) -> crate::Result<Vec<String>> {
        let output = self.generate(prompt, params)?;
        Ok((!output.text().is_empty())
            .then(|| output.into_text())
            .into_iter()
            .collect())
    }
}

fn trim_at_stop(mut text: String, stops: &[String]) -> String {
    if let Some(index) = stops
        .iter()
        .filter(|stop| !stop.is_empty())
        .filter_map(|stop| text.find(stop))
        .min()
    {
        text.truncate(index);
    }
    text
}

fn fallback_chat_template(messages: &[tokenizer::ChatMessage]) -> tokenizer::Result<String> {
    Ok(messages
        .iter()
        .map(|message| format!("{}: {}", message.role(), message.content()))
        .chain(["assistant:".to_string()])
        .collect::<Vec<_>>()
        .join("\n"))
}
